name: Log Analyzer
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - run: echo "The job was triggered by a ${{ github.event_name }} event"
      - name: Check out repository under $GITHUB_WORKSPACE, so workflow can access it
        uses: actions/checkout@v3
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test with unittest
        run: |
          python -m unittest tests.py
      - run: echo "Finished. The job's status is ${{ job.status }}."